In [4]:
import numpy as np

### Easy level numpy questions

In [ ]:
# Question 1

arr1 = np.arange(1,11)
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10]


In [8]:
# Question 2

arr2 = np.array([10,20,30,40,50])
print("Array: ",arr2)
print("Dimensions: ",np.shape(arr2))

Array:  [10 20 30 40 50]
Dimensions:  (5,)


In [11]:
# Question 3

arr3 = np.zeros((2,3))
print(arr3)

[[0. 0. 0.]
 [0. 0. 0.]]


In [13]:
# Question 4

arr4 = np.ones((3,3))
print(f"3x3 Array: \n{arr4}")

3x3 Array: 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [15]:
# Question 5

arr5 = np.arange(0,1.1,0.2)
print(f"Array: {arr5}")

Array: [0.  0.2 0.4 0.6 0.8 1. ]


In [18]:
# Question 6

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(np.shape(arr))

(2, 5)


In [21]:
# Question 7

arr6 = np.array([[1,2,3,4,5,6]])
print(arr6.reshape(2,3))

[[1 2 3]
 [4 5 6]]


In [23]:
# Question 8

arry = np.array([5,10,15,20])
print(arry[1])

10


In [25]:
# Question 9

arrv = np.array([3, 7, 2, 9, 5])
print(arrv.max())

9


In [27]:
# Question 10

arrc = np.array([3, 7, 2, 9, 5])
print(np.sum(arrc))

26


### Medium Level Numpy Questions

In [29]:
# Question 1

arr11 = np.random.randint(1,101,(4,4))
arr11[arr11%2 == 0] = 0
print(arr11)


[[19 39 49  0]
 [55  0 85  0]
 [ 0 51  9 17]
 [49  0 97  0]]


In [32]:
# Question 2

arr12 = np.arange(1,21)
ar = arr12[arr12%3 == 0]
print(ar)

[ 3  6  9 12 15 18]


In [37]:
# Question 3

arr13 = np.random.randint(1,30,(3,3))
sum = arr13.sum(axis=1)
print(f"Array: \n{arr13}")

print(f"Sum of Array: {sum}")

Array: 
[[24 15 26]
 [ 7 15 29]
 [ 3 28  3]]
Sum of Array: [65 51 34]


In [39]:
# Question 4

arr41 = np.random.randint(1,10,(1,7))
arr14 = np.random.randint(1,10,(1,7))

common = np.intersect1d(arr41,arr14)
print(f"Array 1: {arr41}")
print(f"Array 2: {arr14}")
print(f"Common Elements In Both Arrays: {common}")

Array 1: [[3 2 4 3 7 8 1]]
Array 2: [[4 4 1 3 3 6 2]]
Common Elements In Both Arrays: [1 2 3 4]


In [41]:
# Question 5

arr53 = np.eye(5)
print(arr53)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [43]:
# Question 6

arr51 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr51[[0,2]] = arr51[[2,0]]
print(arr51)

[[7 8 9]
 [4 5 6]
 [1 2 3]]
