In [4]:
import numpy as np

In [ ]:
# Question 1

arr1 = np.arange(1,11)
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10]


In [8]:
# Question 2

arr2 = np.array([10,20,30,40,50])
print("Array: ",arr2)
print("Dimensions: ",np.shape(arr2))

Array:  [10 20 30 40 50]
Dimensions:  (5,)


In [11]:
# Question 3

arr3 = np.zeros((2,3))
print(arr3)

[[0. 0. 0.]
 [0. 0. 0.]]


In [13]:
# Question 4

arr4 = np.ones((3,3))
print(f"3x3 Array: \n{arr4}")

3x3 Array: 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [15]:
# Question 5

arr5 = np.arange(0,1.1,0.2)
print(f"Array: {arr5}")

Array: [0.  0.2 0.4 0.6 0.8 1. ]


In [18]:
# Question 6

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(np.shape(arr))

(2, 5)


In [ ]:
# Question 7

