In [4]:
##code evaluating speed,

# in python list

import time

a = [i for i in range(10000000)]
b = [i for i in range(10000000,20000000)]

c = []

start = time.time()
for i in range(len(a)):
    c.append(a[i] + b[i])
print(time.time() - start)

2.3867790699005127


In [5]:
# now code evaluating speed in numpy
import numpy as np

aa = np.arange(10000000)
bb = np.arange(10000000,20000000)

start = time.time()
c = aa + bb
print(time.time() - start)

0.1301407814025879


In [7]:
# now we are comparing that how much memory does python list and numpy list uses,

import sys
ac = [i for i in range(10000000)]
sys.getsizeof(ac)

89095160

In [25]:
# for numpy
av = np.arange(10000000)
sys.getsizeof(av)

80000112

In [11]:
# can also change the dtyoe to reduce memory usage

av = np.arange(10000000, dtype=np.int32)
sys.getsizeof(av)


40000112

In [15]:
a = np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [16]:
# if i want row 0,4,3, i will use fance indexing.

a[[0,4,3]]

array([[ 0,  1,  2,  3],
       [16, 17, 18, 19],
       [12, 13, 14, 15]])

In [18]:
# boolean indexing,

a = np.random.randint(1,100,24).reshape(6,4)
a

array([[95, 40, 53, 89],
       [51, 30, 55, 77],
       [78, 74, 87, 39],
       [98, 11, 74, 44],
       [ 9, 14, 18, 47],
       [52, 63, 82, 67]], dtype=int32)

In [20]:
# finding elements which is greater then 50 in matrix "a",

a>50

array([[ True, False,  True,  True],
       [ True, False,  True,  True],
       [ True,  True,  True, False],
       [ True, False,  True, False],
       [False, False, False, False],
       [ True,  True,  True,  True]])

In [21]:
a[a > 50]

array([95, 53, 89, 51, 55, 77, 78, 74, 87, 98, 74, 52, 63, 82, 67],
      dtype=int32)

In [22]:
# finding even number from matrix a,

a[a % 2 == 0]

array([40, 30, 78, 74, 98, 74, 44, 14, 18, 52, 82], dtype=int32)

In [23]:
# finding even numbers which is greater than 50,

a[(a > 50) & (a % 2 == 0)]

array([78, 74, 98, 74, 52, 82], dtype=int32)

In [24]:
# find all the numbers which is not divisible by 7,

a[~( a % 7 ==0)]

array([95, 40, 53, 89, 51, 30, 55, 78, 74, 87, 39, 11, 74, 44,  9, 18, 47,
       52, 82, 67], dtype=int32)

In [26]:
## claculating sigmoid,

def sigmoid(array):
    return 1/(1 + np.exp(-(array)))

a = np.arange(20)
print(sigmoid(a))



[0.5        0.73105858 0.88079708 0.95257413 0.98201379 0.99330715
 0.99752738 0.99908895 0.99966465 0.99987661 0.9999546  0.9999833
 0.99999386 0.99999774 0.99999917 0.99999969 0.99999989 0.99999996
 0.99999998 0.99999999]
