In [1]:
!pip install numpy

^C


   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
    --------------------------------------- 0.3/12.3 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.3 MB 1.1 MB/s eta 0:00:11
   -- ------------------------------------- 0.8/12.3 MB 1.2 MB/s eta 0:00:10
   --- ------------------------------------ 1.0/12.3 MB 1.2 MB/s eta 0:00:10
   ---- ----------------------------------- 1.3/12.3 MB 1.3 MB/s eta 0:00:09
   ----- ---------------------------------- 1.8/12.3 MB 1.4 MB/s eta 0:00:08
   ------ --------------------------------- 2.1/12.3 MB 1.5 MB/s eta 0:00:08
   -------- ------------------------------- 2.6/12.3 MB 1.5 MB/s eta 0:00:07
   ---------- ----------------------------- 3.1/12.3 MB 1.6 MB/s eta 0:00:06
   ----------- ---------------------------- 3.7/12.3 MB 1.7 MB/s eta 0:00:06
   ------------- -------------------------- 4.2/12.3 MB 1.8 MB/s eta 0:00:05
   --------------- -

In [2]:
# create a array

import numpy as np

arr1 = np.array([10,20,30])
print(arr1)
print(type(arr1))
print(arr1.shape)

[10 20 30]
<class 'numpy.ndarray'>
(3,)


In [9]:
# reshaping an array

arr2 = np.array([1,4,2,5,5])
print(arr2.reshape(1,5))

[[1 4 2 5 5]]


In [8]:
# Numpy vectorised operations
arr3 = np.array([1,2,3,4,5])
arr4 = np.array([10,20,30,40,50])

# element wise addition,
print(f"Addition: {arr3+arr4}")

# element wise substraction,
print(f"Substraction: {arr3-arr4}")

# element wise multiplication,
print(f"Multiplication: {arr3*arr4}")

Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]


In [11]:
# Universal functions
arr = np.array([2,4,3,5,7])

# square root,
print(np.sqrt(arr))

# exponential,
print(np.exp(arr))

# Sine,
print(np.sin(arr))

# natural log,
print(np.log(arr))

[1.41421356 2.         1.73205081 2.23606798 2.64575131]
[   7.3890561    54.59815003   20.08553692  148.4131591  1096.63315843]
[ 0.90929743 -0.7568025   0.14112001 -0.95892427  0.6569866 ]
[0.69314718 1.38629436 1.09861229 1.60943791 1.94591015]


In [3]:
# Creating 3d array

a = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(a)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [5]:
# we can change the dtype also

b = np.array([1,2,3], dtype=bool)
v = np.array([1,2,3], dtype=float)
print(b)
print(v)

[ True  True  True]
[1. 2. 3.]


In [7]:
# np.arange

cb = np.arange(1,13)
print(cb)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [11]:
# we can rehape the array in np.arange also

cc = np.arange(1,10).reshape(3,3)
print(cc)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Array Attributes

In [13]:
a1 = np.arange(10)
a2 = np.arange(12, dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [14]:
#ndim (it shoes the number of dimensions of array)
a3.ndim

3

In [15]:
# shape of array
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

## Changing Data Type

In [18]:
print(a3.dtype)
a3.astype(np.int32)


int64


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

In [19]:
# indexing on 3d array

a6 = np.arange(27).reshape(3,3,3)
print(a6)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [21]:
a6[1,:,:]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [25]:
a6[0,1,:]

array([3, 4, 5])

In [26]:
a6[1,:,1]

array([10, 13, 16])

In [27]:
a6[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [28]:
a6[::2,:5:3,::2]

array([[[ 0,  2]],

       [[18, 20]]])